### ISSUE TITLE
Mapping-Failure: Organization -> missing elements

### ISSUE THREAD

**Issue by ziegm** [ahdis/cda-core-2.0#13]
Mapping CDA -> FHIR
- **Example:** cda-core-2.0\resources\examples\1-Zuweisung zur Radiologischen Diagnostik.xml
- Organization -> **missing** elements
   - Organization.active
   - Organization.type
   - Organization.name -> see Issue #1 
   - Organization.telecom
   - Organization.address

**Comment by oliveregger** [comment]
wo sollten active und type vorkommen?
